source 'https://rubygems.org'

#Core Management
gem 'rails', '4.1.8' #maybe 4.2.0
gem 'sqlite3' #maybe 'pg'

#user management
gem 'devise'
gem 'omniauth', '~> 1.2.2'

#messaging management
gem 'mailboxer'

#Front End Management
gem 'sass-rails'
gem 'bootstrap-sass' #add this
gem 'autoprefixer-rails', '4.0.0.1' #add this
gem 'simple_form' #add this
gem 'font-awesome-sass' #add this
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'ransack'
gem "mini_magick"
gem "refile", require: ["refile/rails", "refile/image_processing"]
gem 'geocoder'
gem 'jquery-turbolinks'
gem 'gmaps4rails'
gem 'will_paginate', '~> 3.0.6'
gem 'will_paginate-bootstrap'

#Testing & Debugging Tools
group :development do
 gem 'annotate'
 gem 'pry-rails'
 gem 'binding_of_caller'
 gem 'better_errors'
 gem 'pry'
 gem 'pry-byebug'
 gem 'thin'
 gem 'spring'
end
