# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e5b3a44e556d4f40e541700a4a69da25efef6390330ebc3451b30c87e3c2b5a8dcc28c2ada7f556e70edc9a10368335c218cb1720d6dd73c793bf1dc092dee2

test:
  secret_key_base: 1390c6199a2d3c2f6e56157ab0fbe69a5ac658b860c9a95709f4c32070626a16fb8372a81e5158025e3f13202b21341c35b9406c5ecaf7f43cdfe3a45977224b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
