source 'https://rubygems.org'

#Core Management
gem 'rails', '4.1.8' #maybe 4.2.0
gem 'sqlite3' #maybe 'pg'

#Front End Management
gem 'sass-rails'
gem 'bootstrap-sass' #add this
gem 'autoprefixer-rails', '4.0.0.1' #add this
gem 'simple_form' #add this
gem 'font-awesome-sass' #add this
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'

#Testing & Debugging Tools
group :development do
 gem 'annotate'
 gem 'pry-rails'
 gem 'binding_of_caller'
 gem 'better_errors'
 gem 'pry'
 gem 'pry-byebug'
 gem 'thin'
 gem 'spring'
end

